// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzxondizgsecijptvqtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6eG9uZGl6Z3NlY2lqcHR2cXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTc5NjIsImV4cCI6MjA2OTk5Mzk2Mn0.YJqIQo1SYrdMrkiJdiE8TZK2iH9mR99_LgqHgjhSmzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});